import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ThemeProvider } from "@/components/ThemeProvider";
import { NavigationHeader } from "@/components/ui/NavigationHeader";
import { ServerStatusNotification } from "@/components/ui/ServerStatusNotification";
import "@mantine/core/styles.css";
import '@mantine/notifications/styles.css';
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { Notifications } from '@mantine/notifications';

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MantineProvider>
          <Notifications position="top-right" zIndex={1000} />
          <ServerStatusNotification />
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NavigationHeader />
            <main className="pt-16 min-h-screen">
              {children}
            </main>
          </ThemeProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
